### ISSUE TITLE
Support for Asynchronous Blocks

### ISSUE THREAD

**Issue by bigeasy** [sstephenson/eco#1]
Asynchronous blocks would be converted into a function that would be invoked as a callback. I've created a Gist that shows [an example that is common to my MySQL development](http://gist.github.com/627244). Before I can invoke a template, I must perform all of the SQL queries to create a JSON model of the document data. Instead, it would be nice to perform those callbacks from within the template.

**Comment by josh** [comment]
Sam and I talked about this while we were implementing eco. An async version of eco would of been more difficult so we just punted on it.

This will require all the helpers apis to change to CPS. I say we line this up for eco 2.0.
