### ISSUE TITLE
linkTo helper isn't prefaced by "@" in documentation

### ISSUE THREAD

**Issue by matthewmueller** [sstephenson/eco#10]
Hi,

I was looking through the readme, and I'm seeing that linkTo doesn't have to be @linkTo. I am hoping there is a way to do this (to easily differentiate between functions and variables), but it seems like all helper functions have to be prefaced with "@".

Does the readme have a mistake? or is there a way to do this?

**Comment by sstephenson** [comment]
Good catch - the `@` was missing. Just pushed a fix.
