### ISSUE TITLE
No multiline blocks?

### ISSUE THREAD

**Issue by akidee** [sstephenson/eco#13]
```
<%- @views.html({
    body: body()
    title: 'xyz'
    css: [ '/static/css/global.css', '/static/css/index.css' ]
}) %>
```

Result:

```
Parse error on line 34: unexpected newline in code block
```

**Comment by sstephenson** [comment]
Correct... CoffeeScript's indentation rules make it hard to support multiline expressions in Eco. 

But I admit I haven't tried implementing it, so feel free to take a shot at it if you're feeling adventurous.

By the way, that line can be written without the parens and braces like this:

```
<%- @views.html body: body(), title: 'xyz', css: ['/static/css/global.css', '/static/css/index.css'] %>
```
