### ISSUE TITLE
Multi-line code blocks

### ISSUE THREAD

**Issue by aseemk** [sstephenson/eco#15]
It's pretty painful not being able to use newlines inside CoffeeScript code blocks!

Here's a simple example test page showing the variety of use cases I miss from other templating engines (like EJS):

https://gist.github.com/966202

Thanks for your consideration. =)

**Comment by sstephenson** [comment]
The problem with multi-line tags in Eco is that we can't know the correct indentation level for lines that follow the tag without doing a full-on parse of the CoffeeScript source. I don't think we want to go there… but if you have an idea for how it can be done, feel free to open a pull request.

(Related: #13)

**Comment by aseemk** [comment]
Hmm... I was assuming you could follow the same rules as Coffee does for multi-line "heredoc" strings:

> The indentation level that begins the heredoc is maintained throughout, so you can keep it all aligned with the body of your code.

http://jashkenas.github.com/coffee-script/#strings

E.g. this is valid CoffeeScript string:

```
html = '''
    <strong>
        cup of coffeescript
    </strong>
'''
```

`html` gets set to this:

```
<strong>
    cup of coffeescript
</strong>
```

So if I have a block of Eco like this:

```
<%
    c = 0
    for foo in bar
        if baz
            c++
%>
```

You would treat the beginning of `c = 0` as the matching indentation level.

Any reason this isn't doable in Eco?

**Comment by aseemk** [comment]
(I hope you don't mind me re-opening for now. If this actually isn't doable or you see a reason not to do it, feel free to close it again. Thanks much!)

**Comment by sstephenson** [comment]
Sorry, it's not in the cards for now. Please feel free to re-open with a patch, though.
