### ISSUE TITLE
Is it possible to run eco in the browser?

### ISSUE THREAD

**Issue by benjaminjackman** [sstephenson/eco#2]
It seems like the code in lib is designed to run within node.js on the server side.

**Comment by sstephenson** [comment]
Yes, compiled Eco templates will run in the browser — no problem. They're just plain JavaScript functions.

The Eco compiler itself runs in the browser in the latest HEAD. You can see it in action here: http://sstephenson.github.com/eco/ (You need to load the CoffeeScript compiler, too, which is quite hefty. The current version is 230 KB.)

To build the browser version of Eco, run `cake dist`. You'll need the `closure-compiler` module from npm. The generated file will be saved in `dist/eco.js`.

I'll leave this open for a bit in case you have any other questions. This will all be documented in the next release.

**Comment by sstephenson** [comment]
Closing the ticket. Feel free to reopen if you need more clarification.

**Comment by joshgoebel** [comment]
Did this ever get documented anywhere?
