### ISSUE TITLE
Helper functions that aren't tied to a model

### ISSUE THREAD

**Issue by sandstrom** [sstephenson/eco#25]
A nice addition would be helper functions that aren't tied to the model. One example would be a function to localize time (see below). If I've understood things correctly that would now require the localizedTime function on each model.  If view/template helpers could be passed as as third argument that would be neat.

_Or perhaps this is already possible, and I've just missed it._

```
var localizedTime = function(utcTime) {
    var offset = (new Date).getTimezoneOffset() / -60;
    // return a localized time (utcTime + offset)
} 
```

**Comment by lagartoflojo** [comment]
You could create and include a JavaScript object that has all these types of helpers. For example, you could have:

``` coffeescript
class Helpers
  localizedTime: (utcTime) ->
    (new Date).getTimezoneOffset() / -60
```

and then in your template:

``` erb
<%= Helpers.localizedTime(@theTime) %>
```

**Comment by sandstrom** [comment]
Good idea!
