### ISSUE TITLE
Line Break / Indentation Error in Windows

### ISSUE THREAD

**Issue by bmarcaur** [sstephenson/eco#29]
Due to some restrictions on my current project I am forced to develop in a windows environment, this being said I have come across a windows specific parsing issue. When I run Eco.compile(File.read ("ANY FILE WITH A CONTROL STRUCTURE") ) I get an unexpected indent error, when I run this same command on my mac it compiles properly. The only control structure that doesn't error out is an if statement without an else statement. I am guessing that this is an issue with the windows line breaks causing the parser to improperly indent, but this is only a guess.

**Comment by rayshih** [comment]
seem that I have the same problem. I'm currently use spinejs and rails, when it come to windows, then the error message occured.
Error: Parse error on line 2: Unexpected 'INDENT'
  (in {Rails_root}/app/assets/javascripts/admin/views/dashboard/contacts.jst.eco)

**Comment by rayshih** [comment]
And I found that it only occur while using block statement like
<% for a in b: %>
<% end %>

**Comment by saulomendonca** [comment]
I have the same problem using block statement 
<% for a in b: %>
<% end %>
in Windows seven

**Comment by thyforhtian** [comment]
I can confirm the problem exists on Windows. Works fine on Linux.

**Comment by arjes** [comment]
Experiencing the same issue

**Comment by TravisBenning** [comment]
Anyone have ideas on a work around / fix? Works fine on my Mac and Linux boxes but not Windows (XP or 7).
Compiler issue? https://github.com/sstephenson/eco/blob/master/lib/compiler.js [line 15?]
Preprocessor? https://github.com/sstephenson/eco/blob/master/lib/preprocessor.js [lines 63-71?]
Util? https://github.com/sstephenson/eco/blob/master/lib/util.js [lines 8-23? maybe due to the way Windows handles end-of-line termination]

Just a few thoughts. Maybe I'm way off but I'd like to help resolve this.

**Comment by bmarcaur** [comment]
Hey guys,

This issue is being caused by a poorly implemented windows javascript compiler. To solve it simply install node and add it to your path. This will stop Eco from falling back on to 'wscript' (I think that is the name) and node handles and compiles Eco templates just fine.

Hope this helps

**Comment by TravisBenning** [comment]
@bmarcaur Thanks for the suggestion. I'll try that out.

**Comment by bmarcaur** [comment]
@TravisBenning No problem, I hope this solves everyones problems.

**Comment by petersonfs** [comment]
@bmarcaur The problem persist. Any solution?

**Comment by bmarcaur** [comment]
@petersonfs My suggestion above is what worked for me, so I haven't tried anything else.

**Comment by petersonfs** [comment]
It doesn't work for me. I'm running windows 7 x64.

**Comment by bmarcaur** [comment]
@petersonfs My environment was win7 x64 as well, I'm sorry this was part of an old project so I haven't needed to work on any other solutions.

**Comment by ewinds** [comment]
node.js worked for my win7 x64.

**Comment by saturday** [comment]
I have this same problem; however I'm on OSX and I have node installed.
