### ISSUE TITLE
Is a template function created?

### ISSUE THREAD

**Issue by akidee** [sstephenson/eco#4]
It seems that render takes the full template string as argument and so it will be evaluated several times instead of prerender a function that will be called. I am not quite sure, but this is not very fast.

**Comment by sstephenson** [comment]
Yes. In Eco 1.0, you can place template files in your load path, and then `require` them to get a compiled template function:

```
require.paths.unshift __dirname + "/app/views"
template = require "projects/index.html.eco"
console.log template name: "My Project"
```

In addition to the require functionality, you can precompile a template with the `eco` function in HEAD:

```
template = eco "Hello <%= @name %>"
console.log template name: "Sam"
```
