### ISSUE TITLE
Can't enclose eco expression within angle brackets

### ISSUE THREAD

**Issue by KyleAMathews** [sstephenson/eco#45]
E.g. if I write `<<%= @email %>>` then nothing is printed.

This does work `< <%= @email %> >` but isn't what I want.

I'm assuming this is a bug? Is there a way to escape "special" characters?

**Comment by sstephenson** [comment]
It's printed, but your browser will treat it as an HTML tag so you won't see it when rendered.

Use `&lt;` and `&gt;` just like you would if you were writing plain HTML.

**Comment by KyleAMathews** [comment]
Haha, oops -- that should of been obvious. Thanks! Love Eco.
