### ISSUE TITLE
Backbone.js and <%=

### ISSUE THREAD

**Issue by superbobry** [sstephenson/eco#49]
Hello, it seems like `<%=` syntax doesn't work well with Backbone models, when a model is used as template context. For example:

``` html
<%= @get("foo") %>
```

is compiled to:

``` javascript
this.escape(this.get("foo"))
```

What's wrong with this? A model [has](http://backbonejs.org/#Model-escape) an `escape()` method, which takes attribute **name** as a single argument, and returns its escaped value. This is obviously not what `eco` is expecting. 

Maybe there's a way to disable this implicit `escape()` lookup?

**Comment by sstephenson** [comment]
You should not pass Backbone models as template context objects. See #36.
