### ISSUE TITLE
Change delimiters

### ISSUE THREAD

**Issue by akidee** [sstephenson/eco#5]
I want to be able to change delimiters - for example to a shorter version like <= >, <- > or mustaches - like in underscore.js: http://documentcloud.github.com/underscore/#template
Is there an official way to do this?

**Comment by sstephenson** [comment]
Not currently. I agree it'd make a nice compile-time option. If you're interested in hacking on it, a good place to start would be [`lib/eco/scanner.coffee`](https://github.com/sstephenson/eco/blob/master/lib/eco/scanner.coffee).
