### ISSUE TITLE
gem install eco

### ISSUE THREAD

**Issue by DouglasAllen** [sstephenson/eco#56]
gem install eco
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: eco requires eco-source (>= 0)

gem install eco-source
ERROR:  Could not find a valid gem 'eco-source' (>= 0) in any repository

If sprockets is dependent on eco then is it deployed to rubygems.org?

**Comment by sstephenson** [comment]
1. Sprockets doesn't depend on Eco.
2. `gem install eco-source --pre`
