### ISSUE TITLE
Does eco support layout for server-side rendering?

### ISSUE THREAD

**Issue by buunguyen** [sstephenson/eco#60]
Something like this

File: content.eco

```
@layout = "layout.eco"

body =
   ... html for the content page
```

If not, how to avoid duplicating common sections (e.g. header, footer etc.) in a site?

**Comment by balupton** [comment]
I think the idea is that eco is a templating engine, rather than an document management system. If you're after layouts, then give [DocPad](http://docpad.org) a go.
