### ISSUE TITLE
Eco Syntax Highlighting

### ISSUE THREAD

**Issue by jonmc12** [sstephenson/eco#8]
What is the best way to get syntax highlighting for eco in my text editor? I use textmate

**Comment by nikgraf** [comment]
Yet I haven't found any textmate bundle, but if you are fine with vim you can use this one: https://github.com/jayferd/eco.vim

**Comment by jonmc12** [comment]
I could not find a way to easily convert vim file to textmate bundle.  However, janmonschke with the Brunch project had a better idea - use the rails syntax highlighter in textmate.

I just cloned my HTML (Rails) bundle and changes the files types as appropriate.

It might be helpful to include a file like this in the git repository so its more obvious.

**Comment by balupton** [comment]
SublimeText highlights it great.
