### ISSUE TITLE
Dist task in Cakefile is outdated

### ISSUE THREAD

**Issue by ghost** [sstephenson/eco#9]
In the Cakefile, the `dist` task refers to files that look like they moved.

`lib/eco.js` doesn't exist, and 
`lib/eco/compiler.coffee`, et. al should probably be `src/eco/compiler.coffee`

**Comment by sstephenson** [comment]
Whoops, good catch. Fixed in a6390dec413f6a2ce2195a463fc5b15ed4ba99d1

**Comment by ghost** [comment]
Thanks for the rapid fix!

The task is supposed to generate `/dist/eco.js`, no? Ran with no errors at a6390de, but didn't make a dist/ folder.

**Comment by sstephenson** [comment]
Do you have the closure-compiler package installed (via npm)?

**Comment by ghost** [comment]
Yup, it crashes otherwise, so I installed it earlier. Still no dice.

Thanks for your help, you don't know how appreciated it is.

**Comment by sstephenson** [comment]
Sure thing. One more question - do you see a node_modules directory after running cake dist?

**Comment by ghost** [comment]
Yup, but it's empty.

All two of us in the office are cheering you on. :)

**Comment by sstephenson** [comment]
What do you see if you run `npm bundle` in the eco directory?

**Comment by ghost** [comment]
It looks like my npm can't find any coffeescript bundle version above 0.9.6. I know Coffee is at 1.0.1, so I'm not sure how come npm cannot see the package.
    npm ERR! Error: No satisfying version found for 'coffee-script'@'>=1.0.1'
    npm ERR! Valid install targets for coffee-script: "latest", "stable", "0.7.0", "0.7.1", "0.7.2", "0.9.0", "0.9.1", "0.9.2", "0.9.3", "0.9.4", "0.9.5", "0.9.6"
    npm ERR!     at /usr/local/lib/node/.npm/npm/0.2.16/package/lib/install.js:143:29

**Comment by sstephenson** [comment]
There we go. You need to upgrade to node >= 0.4 and npm >= 0.3.

**Comment by ghost** [comment]
Wow node moves fast. Thanks so much for your help! 
Hopefully other poor people will use this for instructions.

**Comment by sstephenson** [comment]
Sure thing. I'll try to work on improving the lack of error messages.
